[package]
name = "niji_macros"
edition = "2021"

[lib]
proc-macro = true

[lints.clippy]
pedantic = "warn"

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.109"
