kind = "dark"

[palette]
pink = "#ff79c6"
red = "#ff5555"
orange = "#ffb86c"
yellow = "#f1fa8c"
green = "#50fa7b"
teal = "#6bf5be"
blue = "#8be9fd"
purple = "#bd93f9"
black = "#282a36"
white = "#f8f8f2"

surface = "#44475a"

[ui]
surface = "surface"
