kind = "light"

[palette]
pink = "#990044"
red = "#9d0006"
orange = "#af3a03"
yellow = "#b57614"
green = "#79740e"
teal = "#427b58"
blue = "#076678"
purple = "#8f3f71"
black = "#3c3836"
white = "#fbf1c7"

dark_gray = "#7c6f64"
light_gray = "#928374"
light_red = "#cc241d"
light_green = "#98971a"
light_yellow = "#d79921"
light_blue = "#458588"
light_purple = "#b16286"
light_teal = "#689d6a"

white_1 = "#ebdbb2"

[ui]
surface = "white_1"

[terminal]
dark_black = "white"
dark_red = "light_red"
dark_green = "light_green"
dark_yellow = "light_yellow"
dark_blue = "light_blue"
dark_magenta = "light_purple"
dark_cyan = "light_teal"
dark_white = "dark_gray"
bright_black = "light_gray"
bright_red = "red"
bright_green = "green"
bright_yellow = "yellow"
bright_blue = "blue"
bright_magenta = "purple"
bright_cyan = "teal"
bright_white = "black"
