kind = "dark"

[palette]
pink = "#f4b8e4"
red = "#e78284"
orange = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
blue = "#8caaee"
purple = "#babbf1"
brown = "#eebebe"
black = "#303446"
white = "#c6d0f5"

surface_0 = "#414559"
crust = "#232634"
overlay_0 = "#737994"

[ui]
surface = "surface_0"
border = "overlay_0"
text_light = "#dce0e8"
