kind = "dark"

[palette]
pink = "#f64380"
red = "#fb4934"
orange = "#fe8019"
yellow = "#fabd2f"
green = "#b8bb26"
teal = "#8ec07c"
blue = "#83a598"
purple = "#d3869b"
black = "#282828"
white = "#fbf1c7"

dark_gray = "#928374"
light_gray = "#a89984"
dark_red = "#cc241d"
dark_green = "#98971a"
dark_yellow = "#d79921"
dark_blue = "#458588"
dark_purple = "#b16286"
dark_teal = "#689d6a"

black_1 = "#3c3836"

[ui]
surface = "black_1"

[terminal]
dark_black = "black"
dark_red = "dark_red"
dark_green = "dark_green"
dark_yellow = "dark_yellow"
dark_blue = "dark_blue"
dark_magenta = "dark_purple"
dark_cyan = "dark_teal"
dark_white = "light_gray"
bright_black = "dark_gray"
bright_red = "red"
bright_green = "green"
bright_yellow = "yellow"
bright_blue = "blue"
bright_magenta = "purple"
bright_cyan = "teal"
bright_white = "white"
