[ui]
color_scheme = "dark"
background = "#1a1b26"
text_background = "#c0caf5"
surface = "#414868"
text_surface = "#c0caf5"
primary = "#a9b1d6"
text_primary = "#1a1b26"
secondary = "#73daca"
border = "#1a1b26"
shadow = "#10101080"

success = "#73daca"
text_success = "#e0af68"
info = "#7aa2f7"
text_info = "#1a1b26"
warning = "#e0af68"
text_warning = "#1a1b26"
error = "#f7768e"
text_error = "#1a1b26"

[ui.palette]
blue_light = "#7aa2f7"
blue_dark = "#2959aa"
yellow_light = "#e0af68"
yellow_dark = "#8f5e15"
orange_light = "#ff9e64"
orange_dark = "#965027"
red_light = "#f7768e"
red_dark = "#8c4351"
purple_light = "#bb9af7"
purple_dark = "#5a3e8e"
brown_light = "#cfc9c2"
brown_dark = "#634f30"
neutral_light = "#a9b1d6"
neutral_dark = "#24283b"

[terminal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"
bright_black = "#414868"
bright_red = "#f7768e"
bright_green = "#73daca"
bright_yellow = "#e0af68"
bright_blue = "#7aa2f7"
bright_magenta = "#bb9af7"
bright_cyan = "#7dcfff"
bright_white = "#c0caf5"
