[package]
name = "niji_console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
log = "0.4.25"
parking_lot = "0.12.5"
termcolor = "1.4.1"
