[book]
authors = ["Lina Roether"]
language = "en"
src = "src"
title = "niji Documentation"
description = "Bringing comfortable theming to the tinkerer's desktop"

[output.html]
default-theme = "ayu"
site-url = "/niji/"
git-repository-url = "https://github.com/lina-roether/niji"
