name: Create binary release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release"
  push:
    tags: "v*.*.*"

permissions:
  contents: read

jobs:
  get_release_version:
    runs-on: ubuntu-latest
    outputs:
      version: |
        ${{ github.event.inputs.version || steps.get_latest_tag.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get latest release tag
        id: get_latest_tag
        if: ${{ !github.events.inputs.version }}
        run: |
          TAG_VERSION="$(git describe --tags "$(git rev-list --tags --max-count=1)")"
          echo "version=$TAG_VERSION" >> "$GITHUB_OUTPUT"
  create_release:
    runs-on: ubuntu-latest
    needs: get_release_version
    permissions:
      contents: write
    env:
      RELEASE_VERSION: ${{ needs.get_release_version.outputs.version }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    steps:
      - name: Create release
        run: |
          gh release create "$RELEASE_VERSION" --repo="$GITHUB_REPOSITORY" --title="$RELEASE_VERSION"
