name: Create release PR
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_semver:
    runs-on: ubuntu-latest
    outputs:
      changed: |
        ${{ steps.cog_get_version.outputs.stdout == steps.cog_bump.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get last tag version
        id: cog_get_version
        uses: cocogitto/cocogitto-action@v4.1.0
        with:
          command: get-version
          args: --tag
      - name: Get new semantic version
        id: cog_bump
        uses: cocogitto/cocogitto-action@v4.1.0
        with:
          command: bump
          args: --auto --dry-run
      - name: Print summary
        if: always()
        run: |
          echo "Last tagged: ${{ steps.cog_get_version.outputs.stdout }}" >> "${GITHUB_STEP_SUMMARY}"
          echo "New: ${{ steps.cog_bump.outputs.stdout }}" >> "${GITHUB_STEP_SUMMARY}"

  create_pr:
    needs: check_semver
    if: ${{ needs.check_semver.outputs.changed }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Cache crates
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-edit
        run: cargo install cargo-edit
      - name: Install niji dependencies
        run: |
          sudo apt-get install -y libluajit-5.1-dev
          sudo apt-get install -y just
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Bump version
        id: cog_bump
        uses: cocogitto/cocogitto-action@v4.1.0
        with:
          command: bump
          args: --auto
      - name: Create changelog
        id: cog_changelog
        uses: cocogitto/cocogitto-action@v4
        with:
          command: changelog
          args: --at ${{ steps.cog_bump.outputs.version }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release
          title: "chore: Release ${{ steps.cog_bump.outputs.version }}"
          body: ${{ steps.cog_changelog.outputs.stdout }}
      - name: Print summary
        if: always()
        run:
          echo "${{ steps.cog_bump.outputs.stdout }}" >>
          "${GITHUB_STEP_SUMMARY}"
