[ui]
color_scheme = "light"
background = "#eff1f5"
text_background = "#4c4f69"
surface = "#ccd0da"
text_surface = "#4c4f69"
primary = "#dc8a78"
text_primary = "#eff1f5"
secondary = "#8839ef"
border = "#dce0e8"
shadow = "#21222c80"

success = "#40a02b"
text_success = "#eff1f5"
info = "#1e66f5"
text_info = "#eff1f5"
warning = "#df8e1d"
text_warning = "#eff1f5"
error = "#d20f39"
text_error = "#eff1f5"

[ui.palette]
blue_light = "#89b4fa"
blue_dark = "#1e66f5"
yellow_light = "#f9e2af"
yellow_dark = "#df8e1d"
orange_light = "#fab387"
orange_dark = "#fe640b"
green_light = "#a6e3a1"
green_dark = "#40a02b"
teal_light = "#94e2d5"
teal_dark = "#179299"
red_light = "#f38ba8"
red_dark = "#d20f39"
pink_light = "#f5c2e7"
pink_dark = "#ea76cb"
purple_light = "#cba6f7"
purple_dark = "#8839ef"
brown_light = "#f5e0dc"
brown_dark = "#dc8a78"
neutral_light = "#cad3f5"
neutral_dark = "#1e1e2e"

[terminal]
black = "#9ca0b0"
red = "#e64553"
green = "#179299"
yellow = "#df8e1d"
blue = "#04a5e5"
magenta = "#ea76cb"
cyan = "#209fb5"
white = "#5c5f77"
bright_black = "#6c6f85"
bright_red = "#d20f39"
bright_green = "#40a02b"
bright_yellow = "#fe640b"
bright_blue = "#1e66f5"
bright_magenta = "#7287fd"
bright_cyan = "#179299"
bright_white = "#4c4f69"
