kind = "light"

[palette]
pink = "#ea76cb"
red = "#d20f39"
orange = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
blue = "#1e66f5"
purple = "#8839ef"
black = "#4c4f69"
white = "#eff1f5"

surface_0 = "#ccd0da"
crust = "#dce0e8"
overlay_0 = "#9ca0b0"

[ui]
surface = "surface_0"
border = "overlay_0"
